---
version: '2.0'
services:
  web:
    image: 'ghcr.io/charlesjudith/woof-api:0.0.1'
    expose:
      - port: 5000
        as: 80
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.2
        memory:
          size: 256Mi
        storage:
          size: 512Mb
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
